### ISSUE TITLE
Duplicate buffers with smart edit

### ISSUE THREAD

**Issue by spapanik** [lambdalisue/vim-suda#51] opened 2022-09-15 10:57 UTC
Adding

```let g:suda_smart_edit = 1```
 
has a strange behaviour: Editing a file that I have no write access, eg /etc/hosts from an open nvim (ie with `:e /etc/hosts`) works fine, but from outside (ie with `nvim /etc/hosts` from the terminal) leads to two open buffers, the suda and the non-suda one.

**Comment by lambdalisue** [comment] 2022-10-05 09:25
Please provide a minimal vimrc and minimal reproduction steps

**Comment by spapanik** [comment] 2022-10-11 09:18
After cleaning up my plugins, the minimal `init.vim` is:
```vim
set nocompatible

call plug#begin()
Plug 'bogado/file-line'
Plug 'lambdalisue/suda.vim'
call plug#end()

let g:suda_smart_edit = 1
```

opening a file that requires sudo to write to it, eg by `nvim /etc/hosts` will open two buffers as can be seen by `:ls`:

```
:ls
  2 #h   "suda:///etc/hosts"            line 1
  3 %a=  "/etc/hosts"                   line 1
```

instead of just one, and the active buffer is the ReadOnly one.

**Comment by lambdalisue** [comment] 2022-10-14 18:47
Got it. Well, it's kinda bug thanks 👍

**Comment by lambdalisue** [comment] 2022-10-14 18:48
https://github.com/lambdalisue/suda.vim/blob/6bffe36862faa601d2de7e54f6e85c1435e832d0/autoload/suda.vim#L236

It seems the previous buffer is removed... Hum...

**Comment by lambdalisue** [comment] 2024-12-06 17:07
I could not reproduce it anymore so I closed this. Feel free to re-open it if my observation is wrong.

**Closed as completed by lambdalisue** 2024-12-06 17:07 UTC
Labels: bug
